### ISSUE TITLE
Unable to login, Cookie issue?

### ISSUE THREAD

**Issue by raducostea** [troydavisson/PHRETS#62]
I am having trouble login in to a rets server and i think is something related to cookies. If i use curl command line using a cookie jar file it works (Important: if i dont use a cookie file its not working)
### Here is the debug log from the phrets.

[2015-04-29 02:43:23] PHRETS.DEBUG: Loading Monolog\Logger logger [] []
[2015-04-29 02:43:23] PHRETS.DEBUG: Sending HTTP Request for https://rets.crmls.org/contact/rets/login (Login) {"cookies":true,"debug":true} []
- About to connect() to rets.crmls.org port 443 (#0)
-   Trying 209.80.40.144...
- Connected to rets.crmls.org (209.80.40.144) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: /home/radu/zsuite-dev/vendor/guzzlehttp/guzzle/src/cacert.pem
  CApath: none
- SSL connection using RC4-MD5
- Server certificate:
-        subject: C=US; ST=California; L=San Dimas; O=California Regional Multiple Listing Service, Inc; CN=rets.crmls.org
-        start date: 2015-04-03 21:14:07 GMT
-        expire date: 2017-04-04 12:52:25 GMT
-        subjectAltName: rets.crmls.org matched
-        issuer: C=US; O=Entrust, Inc.; OU=See www.entrust.net/legal-terms; OU=(c) 2012 Entrust, Inc. - for authorized use only; CN=Entrust Certification Authority - L1K
-        SSL certificate verify ok.
- Server auth using Digest with user 'USER'
  > GET /contact/rets/login HTTP/1.1
  Accept-Encoding: gzip
  Host: rets.crmls.org
  RETS-Version: RETS/1.7.2

< HTTP/1.1 401 Unauthorized
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=37C5D5128B409C50F0512630F5576E38; Path=/contact
< Set-Cookie: JSESSIONID=37C5D5128B409C50F0512630F5576E38; Path=/contact
< MIME-Version: 1.0
< Cache-Control: private
< RETS-Version: RETS/1.7.2
< WWW-Authenticate: Digest realm="rets@retsiq.com",qop="auth",nonce="a046d8c8edf907fac4c9075805c9d039", opaque="9885bba5142ce"
< Content-Type: text/html;charset=utf-8
< Content-Length: 954
< Date: Wed, 29 Apr 2015 09:43:22 GMT
<
- Ignoring the response-body
- Connection #0 to host rets.crmls.org left intact
- Issue another request to this URL: 'https://rets.crmls.org/contact/rets/login'
- Found bundle for host rets.crmls.org: 0x1aa411d0
- Re-using existing connection! (#0) with host rets.crmls.org
- Connected to rets.crmls.org (209.80.40.144) port 443 (#0)
- Server auth using Digest with user 'USER'
  > GET /contact/rets/login HTTP/1.1
  Authorization: Digest username="USER", realm="rets@retsiq.com", nonce="a046d8c8edf907fac4c9075805c9d039", uri="/contact/rets/login", cnonce="ICAgICAgICAgICAgICAgICAgICAgICAgMzc4OTY0MzQ=", nc=00000001, qop=auth, response="ae40d6c00dfb2779b84325a974eb8ba4", opaque="9885bba5142ce"
  Accept-Encoding: gzip
  Host: rets.crmls.org
  RETS-Version: RETS/1.7.2

< HTTP/1.1 401 Unauthorized
< Server: Apache-Coyote/1.1
< Set-Cookie: JSESSIONID=1CAB2481E7B7DCD20C72E5F3CE4380F9; Path=/contact
< Set-Cookie: JSESSIONID=1CAB2481E7B7DCD20C72E5F3CE4380F9; Path=/contact
< MIME-Version: 1.0
< Cache-Control: private
< RETS-Version: RETS/1.7.2
- Authentication problem. Ignoring this.
  < WWW-Authenticate: Digest realm="rets@retsiq.com",qop="auth",nonce="243f4e6d676cdc7b5367a41f2b080102", opaque="da1d19d00e2c4"
  < Content-Type: text/html;charset=utf-8
  < Content-Length: 954
  < Date: Wed, 29 Apr 2015 09:43:23 GMT
  <
- Connection #0 to host rets.crmls.org left intact
  PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://rets.crmls.org/contact/rets/login [status code] 401 [reason phrase] Unauthorized' in /home/radu/zsuite-dev/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:68
### This is the request using curl command line and a cookie jar file.
- About to connect() to rets.crmls.org port 443 (#0)
-   Trying 209.80.40.144...
- Connected to rets.crmls.org (209.80.40.144) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using RC4-MD5
- Server certificate:
-        subject: C=US; ST=California; L=San Dimas; O=California Regional Multiple Listing Service, Inc; CN=rets.crmls.org
-        start date: 2015-04-03 21:14:07 GMT
-        expire date: 2017-04-04 12:52:25 GMT
-        subjectAltName: rets.crmls.org matched
-        issuer: C=US; O=Entrust, Inc.; OU=See www.entrust.net/legal-terms; OU=(c) 2012 Entrust, Inc. - for authorized use only; CN=Entrust Certification Authority - L1K
-        SSL certificate verify ok.
- Server auth using Digest with user 'USER'
  > GET /contact/rets/login HTTP/1.1
  > User-Agent: curl/7.29.0
  > Host: rets.crmls.org
  > Accept: _/_
  >
  < HTTP/1.1 401 Unauthorized
  < Server: Apache-Coyote/1.1
- Added cookie JSESSIONID="13DDA9E8A272F02041C23DA2CB14CF66" for domain rets.crmls.org, path /contact, expire 0
  < Set-Cookie: JSESSIONID=13DDA9E8A272F02041C23DA2CB14CF66; Path=/contact
- Replaced cookie JSESSIONID="13DDA9E8A272F02041C23DA2CB14CF66" for domain rets.crmls.org, path /contact, expire 0
  < Set-Cookie: JSESSIONID=13DDA9E8A272F02041C23DA2CB14CF66; Path=/contact
  < MIME-Version: 1.0
  < Cache-Control: private
  < RETS-Version: RETS/1.7.2
  < WWW-Authenticate: Digest realm="rets@retsiq.com",qop="auth",nonce="eece9c0ac2820413b7d80e47a1f4789a", opaque="2a7dd40718d3f"
  < Content-Type: text/html;charset=utf-8
  < Content-Length: 954
  < Date: Wed, 29 Apr 2015 09:50:20 GMT
  <
- Ignoring the response-body
- Connection #0 to host rets.crmls.org left intact
- Issue another request to this URL: 'https://rets.crmls.org/contact/rets/login'
- Found bundle for host rets.crmls.org: 0x4c92b60
- Re-using existing connection! (#0) with host rets.crmls.org
- Connected to rets.crmls.org (209.80.40.144) port 443 (#0)
- Server auth using Digest with user 'USER'
  > GET /contact/rets/login HTTP/1.1
  > Authorization: Digest username="USER", realm="rets@retsiq.com", nonce="eece9c0ac2820413b7d80e47a1f4789a", uri="/contact/rets/login", cnonce="ICAgICAgICAgICAgICAgICAgICAgICAgMzczNTIzODc=", nc=00000001, qop=auth, response="cd4d49644270dccffec3279472b017a0", opaque="2a7dd40718d3f"
  > User-Agent: curl/7.29.0
  > Host: rets.crmls.org
  > Accept: _/_
  > Cookie: JSESSIONID=13DDA9E8A272F02041C23DA2CB14CF66
  >
  < HTTP/1.1 200 OK
  < Server: Apache-Coyote/1.1
- Replaced cookie JSESSIONID="13DDA9E8A272F02041C23DA2CB14CF66" for domain rets.crmls.org, path /contact, expire 0
  < Set-Cookie: JSESSIONID=13DDA9E8A272F02041C23DA2CB14CF66; Path=/contact
  < MIME-Version: 1.0
  < Cache-Control: private
  < RETS-Version: RETS/1.7.2
  < WWW-Authenticate: Digest realm="rets@retsiq.com",qop="auth",nonce="5dabdbe626af5b6bda7ec08ef333a2f7", opaque="08346b25456d0"
- Added cookie RETS-Session-ID="bff2c4d1714c79cf94c50e215c159d9214d049593af" for domain rets.crmls.org, path /contact, expire 0
  < Set-Cookie: RETS-Session-ID=bff2c4d1714c79cf94c50e215c159d9214d049593af; Path=/contact
  < Content-Type: text/xml
  < Content-Length: 595
  < Date: Wed, 29 Apr 2015 09:50:21 GMT
  <
  <RETS ReplyCode="0" ReplyText="Operation Successful">
  <RETS-RESPONSE>
  MemberName=User Inc.
  User=User ,0,IDXFeed,User 
  Broker=
  MetadataVersion=1.00.00014
  MetadataTimestamp=2015-04-06T16:06:51
  MinMetadataTimestamp=2015-04-06T16:06:51
  TimeoutSeconds=1800000
  Action=/contact/rets/action
  GetMetadata=/contact/rets/getMetadata
  GetObject=/contact/rets/getObject
  Login=/contact/rets/login
  Logout=/contact/rets/logout
  X-PostObject=/contact/rets/postObject
  Search=/contact/rets/search
  X-Selector=/contact/rets/selector
  Update=/contact/rets/update
  </RETS-RESPONSE>
  </RETS>
- Connection #0 to host rets.crmls.org left intact
### First request

> GET /contact/rets/login HTTP/1.1
> Authorization: Digest username="USER", realm="rets@retsiq.com", nonce="a046d8c8edf907fac4c9075805c9d039", uri="/contact/rets/login", cnonce="ICAgICAgICAgICAgICAgICAgICAgICAgMzc4OTY0MzQ=", nc=00000001, qop=auth, response="ae40d6c00dfb2779b84325a974eb8ba4", opaque="9885bba5142ce"
> Accept-Encoding: gzip
> Host: rets.crmls.org
> RETS-Version: RETS/1.7.2
### Second request

> Authorization: Digest username="USER", realm="rets@retsiq.com", nonce="eece9c0ac2820413b7d80e47a1f4789a", uri="/contact/rets/login", cnonce="ICAgICAgICAgICAgICAgICAgICAgICAgMzczNTIzODc=", nc=00000001, qop=auth, response="cd4d49644270dccffec3279472b017a0", opaque="2a7dd40718d3f"
> User-Agent: curl/7.29.0
> Host: rets.crmls.org
> Accept: _/_
> Cookie: JSESSIONID=13DDA9E8A272F02041C23DA2CB14CF66

So you can actually see that the first request is missing the cookie resulting in a 401 error.

**Comment by mikebronner** [comment]
@raducostea Have you made any progress on this? I am able to log into other MLS' just fine, but CRMLS is always giving me "401 Unauthorized". Any ideas?

**Comment by raducostea** [comment]
@mikebronner  not really, i just gave up and i am using the old version of the rets.

**Comment by mikebronner** [comment]
I did figure a work-around (really poor though) that works for me so far:

```php
        $rets = new Rets($retsConfig);
        $rets->setLogger($log);

        try {
            $rets->Login();
        } catch (Exception $e) {
            $rets->Login();
        }
```

To me it looks like a server issue with CRMLS (I've had trouble with their servers in the past). You note about requiring a second attempt triggered this idea, and it seems to work.

**Comment by joselara** [comment]
I believe they go more into depth about the issue here: https://github.com/guzzle/guzzle/issues/1153 and PR has been submitted for Guzzle 6.1.

**Comment by ooglek** [comment]
This is still a problem. PHRETS/2.0 requires guzzle 4 or 5, but not 6, explicitly. Even if the fix that is suspected of fixing the problem is resolved in 6.1, Troy would need to update PHRETS/2.0 to support Guzzle 6.x.

@troydavisson Any chance that will happen? Are you actively making changes to PHRETS/2.0?

Thanks @mikebronner for the work-around -- agreed it is hacky, but I suspect that a work-around could be put in place that is more clean, such as doing the login again and checking the response to GetSystemMetadata() before actually believing the exception.

**Comment by troydavisson** [comment]
I've started a new branch which changes PHRETS 2.x to support Guzzle 6+.  Please try out the `2.3.x-dev` Composer version and report back with any problems you run into.

**Comment by ilamp** [comment]
I tried 2.3.x-dev but it didn't help either. I've narrowed it down to a missing cookie. Request is not setting the cookie with the request. It might have something to do with the Cookie jar or perhaps it's not included.

Another thing I noticed is that the cookie has a path and it could be that guzzle has a bug which doesn't work properly when a path is supplied for the cookie.

**Comment by ilamp** [comment]
Another thing I noticed is that the server is sending two "Set-Cookie" headers in the response.

**Comment by ilamp** [comment]
Yup, it's seems that when doing Digest authentication through Guzzle it does not include the cookie required for some servers.

**Comment by Aranjedeath** [comment]
Hi those of you with the cookie problem might check this solution. (someone else's post)

https://groups.google.com/forum/#!topic/phrets/fr5A3Klgwys

**Comment by troydavisson** [comment]
Thank you for that link.  I missed that post in the group.

I've pushed a change to the 2.3-dev branch which should fix this (at least temporarily until Guzzle does something different).

**Comment by troydavisson** [comment]
Version 2.3 has been released and includes some changes which should address this.  Please give the latest version a try if able.

**Comment by anaya-prog** [comment]
I am trying version 2.3 but still getting same issue. Anyone have found solution for this?
